### ISSUE TITLE
wrong date

### ISSUE THREAD

**Issue by Julcsi69** [paylike/sdk#15]
I made a trial purchase.
Payment failed.
I checked the transaction.
For credit card details at the expiration date
each time 06 is listed instead of 05.
I tried another number,
I wrote 04 instead of 05.
And so the system shows 05, which is the correct number.
I marked this in green in the picture.
But the transaction still failed.
Please correct the problem.
Thank you for your help.

![hiba](https://user-images.githubusercontent.com/78219459/122642615-9df72f80-d10b-11eb-8375-619f5cb32f28.png)

**Comment by tjconcept** [comment]
Hi @Julcsi69 

This is a display issue in the dashboard caused by a timezone mismatch. It *does not* affect payments processing and so is *not* the reason for failed payments. You can fetch the transaction from the API to see the real card expiry date.
We are aware of the display issue and working on a fix.

**Comment by Julcsi69** [comment]
Hello,
the main problem is that the transaction does not take place.
It is not possible to pay with the credit card function.
Please rectify this.

**Comment by tjconcept** [comment]
Hi again,

Please reach out to our support at hello@paylike.io with the transaction IDs such that we can have a look at the cause.
