### ISSUE TITLE
For the locale, is there a specific lists, iso format for the codes?

### ISSUE THREAD

**Issue by ionutcalara** [paylike/sdk#9]

**Comment by tjconcept** [comment]
It's standard ISO 3166-1 alpha 2 (https://en.wikipedia.org/wiki/ISO_3166-1). There's a JSON and CSV list at https://github.com/srcagency/iso-3166-1-codes/blob/master/data.csv.

The currently supported locales are:
- `da`
- `en`
- `es`
- `fi`
- `fr`
- `nl`
- `no`
- `ro`
- `sv`
- `sk`
- `kl`
- `de`
- `pl`
- `et`
- `bg`
- `hu`
- `cs`

If you ever wonder about one, test it, if support is lacking, open an issue and we will work on supporting it.

**Comment by ionutcalara** [comment]
Ok, i had been testing randomly with the languages and some of them didn't work, and i wasn't sure if its the format or something else. Thank you.

**Comment by Man-of-Irtha** [comment]
Hello Ionuț,
Good job with the VM3 Paylike plugin for the recent versions of VM.
I'd like to ask if it's possible to add the price of the transaction to the amount, and if there can be created options to choose which order statuses to be created and when (at which step of placing the order). For instance, I see the order state when someone places an order is "Pending", instead of "Confirmed by shopper" (it's kinda awkward to send emails to the cursomers with this status).
Other useful options would be choosing this method for specific categories (e.g. if the basket contains ebooks, paylike could be chosen, otherwise, if there is no digital product in the cart, some might prefer cash on delivery etc.)

**Comment by ionutcalara** [comment]
Hi @arcturus-one can you please confirm that you are talking about this plugin: https://github.com/paylike/plugin-virtuemart

**Comment by Man-of-Irtha** [comment]
Yes, that's the one I'm talking about.

**Comment by ionutcalara** [comment]
Can you please send me an email at ionut@paylike.io and we can continue the discussion there? @arcturus-one
